version: '3'

services:
  crumbline:
    build:
      context: .
      args:
        - ADMIN_USER=admin
        - ADMIN_EMAIL=admin@example.com
        - ADMIN_PASSWORD=changeme123  # Change this!
    environment:
      - SECRET_KEY=changethissecretkey
      - DATABASE_URL=sqlite+aiosqlite:///feeds.db
      - HOST=0.0.0.0
      - PORT=8181
      - DEBUG=False
    ports:
      - "8181:8181"
    volumes:
      - ./feeds.db:/app/feeds.db
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crumbline.rule=Host(`rss.outeniquastudios.com`)"
      - "traefik.http.services.crumbline.loadbalancer.server.port=8181"

networks:
  web:
    external: true
