version: '3'

services:
  crumbline:
    build:
      context: .
      args:
        - ADMIN_USER=admin
        - ADMIN_EMAIL=admin@example.com
        - ADMIN_PASSWORD=changeme123  # Change this!
    environment:
      - SECRET_KEY=changethissecretkey
      - DATABASE_URL=sqlite+aiosqlite:///feeds.db
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
    ports:
      - "8000:8000"
    volumes:
      - ./feeds.db:/app/feeds.db
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_crumbline.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - crumbline
    restart: always
